#!/usr/bin/env python3
"""Generate complete source-backed Flyto2 AI reference documents."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "reference"
PYTHON_REFERENCE = REFERENCE / "python"
NOTICE = "> Generated by `python3 scripts/generate_reference.py`. Do not edit manually."


def md(value: str) -> str:
    return value.replace("|", "\\|")


def parse(path: Path) -> ast.Module | None:
    try:
        return ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return None


def annotation(node: ast.expr | None) -> str:
    return ast.unparse(node) if node is not None else ""


def signature(node: ast.FunctionDef | ast.AsyncFunctionDef, *, method: bool) -> str:
    args = node.args
    values: list[str] = []
    positional = [*args.posonlyargs, *args.args]
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    for arg, default in zip(positional, defaults):
        if method and arg.arg in {"self", "cls"}:
            continue
        value = arg.arg + (f": {annotation(arg.annotation)}" if arg.annotation else "")
        if default is not None:
            value += f" = {ast.unparse(default)}"
        values.append(value)
    if args.vararg:
        values.append(f"*{args.vararg.arg}")
    elif args.kwonlyargs:
        values.append("*")
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        value = arg.arg + (f": {annotation(arg.annotation)}" if arg.annotation else "")
        if default is not None:
            value += f" = {ast.unparse(default)}"
        values.append(value)
    if args.kwarg:
        values.append(f"**{args.kwarg.arg}")
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    result = f"{prefix}{node.name}({', '.join(values)})"
    if node.returns:
        result += f" -> {annotation(node.returns)}"
    return result


def purpose(node: ast.AST, owner: str | None = None) -> str:
    doc = ast.get_docstring(node)
    if doc:
        value = " ".join(part.strip() for part in doc.splitlines() if part.strip())
        return value.split(". ", 1)[0].rstrip(".") + "."
    name = getattr(node, "name", "symbol")
    visibility = "Internal" if name.startswith("_") else "Public"
    subject = f"`{owner}`" if owner else "this module"
    known = {
        "to_dict": f"Serialize {subject} to a dictionary.",
        "from_dict": f"Construct {subject} from a dictionary.",
        "start": f"Start {subject} and its owned resources.",
        "stop": f"Stop {subject} and release its owned resources.",
        "close": f"Release resources owned by {subject}.",
        "run": f"Run the primary operation implemented by {subject}.",
        "chat": f"Execute a provider-backed chat turn through {subject}.",
        "send": f"Send a message through {subject}.",
    }
    return known.get(name, f"{visibility} `{name}` implementation on {subject}; the linked source is authoritative.")


def source_link(path: Path, line: int, depth: int = 3) -> str:
    rel = path.relative_to(ROOT).as_posix()
    return f"[`{rel}:{line}`]({'../' * depth}{rel}#L{line})"


def module_nodes(tree: ast.Module) -> list[ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef]:
    top_level = [node for node in tree.body if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))]
    top_level_ids = {id(node) for node in top_level}
    nested_classes = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.ClassDef) and id(node) not in top_level_ids
    ]
    return sorted([*top_level, *nested_classes], key=lambda node: node.lineno)


def group_for(path: Path) -> str:
    rel = path.relative_to(ROOT)
    return rel.parts[1] if len(rel.parts) > 2 else "package-root"


def render_group(group: str, paths: list[Path]) -> str:
    lines = [f"# Python Symbols: {group}", "", NOTICE, "", "Includes public and underscore-prefixed implementation symbols plus nested classes so every declared callable remains discoverable.", ""]
    symbol_count = 0
    method_count = 0
    for path in paths:
        tree = parse(path)
        if tree is None:
            continue
        nodes = module_nodes(tree)
        if not nodes:
            continue
        module = ".".join(path.relative_to(ROOT).with_suffix("").parts)
        lines.extend([f"## `{module}`", ""])
        for node in nodes:
            symbol_count += 1
            visibility = "internal" if node.name.startswith("_") else "public"
            if isinstance(node, ast.ClassDef):
                bases = ", ".join(ast.unparse(base) for base in node.bases)
                declaration = f"class {node.name}" + (f"({bases})" if bases else "")
                lines.extend([f"### `{node.name}` ({visibility})", "", f"`{declaration}`", "", f"Source: {source_link(path, node.lineno)}", "", purpose(node), ""])
                methods = [item for item in node.body if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))]
                if methods:
                    lines.extend(["| Method | Visibility | Purpose | Source |", "|---|---|---|---|"])
                    for method in methods:
                        method_count += 1
                        sig = signature(method, method=True).replace("|", "\\|")
                        description = purpose(method, node.name).replace("|", "\\|")
                        method_visibility = "internal" if method.name.startswith("_") else "public"
                        lines.append(f"| `{sig}` | {method_visibility} | {description} | {source_link(path, method.lineno)} |")
                    lines.append("")
            else:
                sig = signature(node, method=False)
                lines.extend([f"### `{node.name}` ({visibility})", "", f"`{sig}`  ", f"Source: {source_link(path, node.lineno)}", "", purpose(node), ""])
    lines[5:5] = [f"Inventory: **{symbol_count} declared symbols** and **{method_count} class methods**.", ""]
    return "\n".join(lines).rstrip() + "\n"


def python_references() -> dict[Path, str]:
    grouped: dict[str, list[Path]] = defaultdict(list)
    for path in sorted((ROOT / "flyto_ai").rglob("*.py")):
        tree = parse(path)
        if tree and module_nodes(tree):
            grouped[group_for(path)].append(path)
    result: dict[Path, str] = {}
    index = ["# Python Symbol Index", "", NOTICE, "", "All module-level functions/classes, nested classes, and direct class methods are included, including internal implementation symbols.", ""]
    for group, paths in sorted(grouped.items()):
        filename = f"{group}.md"
        top = sum(len(module_nodes(parse(path))) for path in paths if parse(path))
        methods = sum(
            sum(len([item for item in node.body if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))]) for node in module_nodes(tree) if isinstance(node, ast.ClassDef))
            for path in paths
            if (tree := parse(path)) is not None
        )
        index.append(f"- [{group}]({filename}): {len(paths)} modules, {top} top-level symbols, {methods} methods")
        result[PYTHON_REFERENCE / filename] = render_group(group, paths)
    result[PYTHON_REFERENCE / "README.md"] = "\n".join(index).rstrip() + "\n"
    return result


def environment_reference() -> str:
    observations: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for path in [*sorted((ROOT / "flyto_ai").rglob("*.py")), *sorted((ROOT / "scripts").rglob("*.py"))]:
        tree = parse(path)
        if tree is None:
            continue
        rel = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call) or not node.args:
                continue
            called = ast.unparse(node.func)
            if called not in {"os.getenv", "_os.getenv", "os.environ.get", "environ.get"}:
                continue
            key = node.args[0]
            if not isinstance(key, ast.Constant) or not isinstance(key.value, str) or not re.fullmatch(r"[A-Z][A-Z0-9_]+", key.value):
                continue
            default = ast.unparse(node.args[1]) if len(node.args) > 1 else "required/None"
            observations[key.value].add((default, rel))
    lines = ["# Environment Variable Reference", "", NOTICE, "", "Every statically named environment read in package and Python scripts. Credentials belong in deployment secrets, never committed files.", "", "| Variable | Observed defaults | Owners |", "|---|---|---|"]
    for key, values in sorted(observations.items()):
        defaults = ", ".join(sorted({value[0] for value in values})).replace("|", "\\|")
        owners = ", ".join(f"`{value}`" for value in sorted({value[1] for value in values}))
        lines.append(f"| `{key}` | `{defaults}` | {owners} |")
    return "\n".join(lines).rstrip() + "\n"


def cli_reference() -> str:
    path = ROOT / "flyto_ai" / "cli.py"
    lines_source = path.read_text(encoding="utf-8").splitlines()
    rows: list[tuple[str, str, str, int]] = []
    parser_vars: dict[str, str] = {"parser": "root", "sub": "root"}
    for index, line in enumerate(lines_source, 1):
        parser = re.search(r"(\w+)\s*=\s*\w+\.add_parser\(\s*['\"]([^'\"]+)['\"](?:,\s*help=['\"]([^'\"]*)['\"])?", line)
        if parser:
            parser_vars[parser.group(1)] = parser.group(2)
            rows.append((parser.group(2), "command", parser.group(3) or "Subcommand", index))
            continue
        direct = re.search(r"\w+\.add_parser\(\s*['\"]([^'\"]+)['\"](?:,\s*help=['\"]([^'\"]*)['\"])?", line)
        if direct:
            rows.append((direct.group(1), "command", direct.group(2) or "Subcommand", index))
            continue
        argument = re.search(r"(\w+)\.add_argument\((.+)", line)
        if argument:
            owner = parser_vars.get(argument.group(1), argument.group(1))
            expression = argument.group(2)
            names = ", ".join(re.findall(r"['\"]([^'\"]+)['\"]", expression)[:2]) or "dynamic"
            help_match = re.search(r"help=['\"]([^'\"]*)['\"]", expression)
            rows.append((owner, names, help_match.group(1) if help_match else "See argparse declaration for behavior/default.", index))
    output = ["# CLI Reference", "", NOTICE, "", "Entrypoints: `flyto-ai` and `python -m flyto_ai`. `flyto-ai-mcp` starts the STDIO MCP server.", "", "| Command owner | Command / option | Purpose | Source |", "|---|---|---|---|"]
    for owner, item, description, line in rows:
        output.append(f"| `{owner}` | `{item}` | {md(description)} | {source_link(path, line, depth=2)} |")
    return "\n".join(output).rstrip() + "\n"


def tool_reference() -> str:
    rows: list[tuple[str, str, str, int]] = []
    for path in sorted((ROOT / "flyto_ai" / "tools").glob("*.py")) + [ROOT / "flyto_ai" / "mcp_server.py"]:
        tree = parse(path)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Dict):
                continue
            values = {}
            for key, value in zip(node.keys, node.values):
                if isinstance(key, ast.Constant) and isinstance(key.value, str):
                    values[key.value] = value
            name_node = values.get("name")
            if not isinstance(name_node, ast.Constant) or not isinstance(name_node.value, str):
                continue
            description_node = values.get("description")
            description = description_node.value if isinstance(description_node, ast.Constant) and isinstance(description_node.value, str) else "Tool or protocol definition."
            rows.append((name_node.value, description.replace("\n", " "), path.relative_to(ROOT).as_posix(), node.lineno))
    unique = sorted(set(rows), key=lambda row: (row[0], row[2], row[3]))
    lines = ["# Tool And MCP Reference", "", NOTICE, "", "Static Flyto2 AI tool definitions. Registry-backed `flyto-core` tools are discovered at runtime and described by the capability manifest rather than copied here.", "", "| Tool | Responsibility | Owner | Source |", "|---|---|---|---|"]
    for name, description, rel, line in unique:
        lines.append(f"| `{name}` | {md(description)} | `{rel}` | {source_link(ROOT / rel, line, depth=2)} |")
    return "\n".join(lines).rstrip() + "\n"


def scripts_reference() -> str:
    lines = ["# Maintainer Script Reference", "", NOTICE, "", "Scripts are operator tools, not stable Python APIs. Review side effects and required credentials before use.", "", "| Script | Purpose |", "|---|---|"]
    for path in sorted((ROOT / "scripts").iterdir()):
        if not path.is_file() or path.name == Path(__file__).name:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if path.suffix == ".py" and (tree := parse(path)) is not None:
            description = ast.get_docstring(tree) or "Python maintainer utility."
        else:
            description = next((line.lstrip("# ").strip() for line in text.splitlines() if line.startswith("#") and not line.startswith("#!")), "Shell maintainer utility.")
        lines.append(f"| [`{path.name}`](../../scripts/{path.name}) | {md(' '.join(description.split()))} |")
    return "\n".join(lines).rstrip() + "\n"


def index_reference() -> str:
    return """# Generated Reference

> Generated by `python3 scripts/generate_reference.py`. Do not edit manually.

- [Python symbols](python/README.md): every top-level function/class and direct class method, including internal symbols.
- [CLI](cli.md): commands and options declared by the CLI parser.
- [Tools and MCP](tools-and-mcp.md): static AI/MCP tool definitions and runtime discovery boundary.
- [Environment](environment.md): every statically named environment read.
- [Maintainer scripts](scripts.md): release/demo and other operator utilities.

Run `python3 scripts/generate_reference.py`; CI uses `--check` to reject drift.
"""


def outputs() -> dict[Path, str]:
    result = python_references()
    result[REFERENCE / "README.md"] = index_reference()
    result[REFERENCE / "cli.md"] = cli_reference()
    result[REFERENCE / "tools-and-mcp.md"] = tool_reference()
    result[REFERENCE / "environment.md"] = environment_reference()
    result[REFERENCE / "scripts.md"] = scripts_reference()
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = outputs()
    if args.check:
        stale = [path for path, content in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        extras = [path for path in PYTHON_REFERENCE.glob("*.md") if path not in expected]
        if stale or extras:
            for path in [*stale, *extras]:
                print(f"stale generated reference: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"{len(expected)} generated reference files are current")
        return 0
    if PYTHON_REFERENCE.exists():
        for path in PYTHON_REFERENCE.glob("*.md"):
            path.unlink()
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(expected)} generated reference files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
