#!/usr/bin/env python3
"""Generate complete source-backed Flyto2 AI reference documents."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "reference"
PYTHON_REFERENCE = REFERENCE / "python"
NOTICE = "> Generated by `python3 scripts/generate_reference.py`. Do not edit manually."
RESERVED_INSTRUCTION_FILENAMES = frozenset({
    "agents.md",
    "claude.md",
    "gemini.md",
})


def md(value: str) -> str:
    return value.replace("|", "\\|")


def parse(path: Path) -> ast.Module | None:
    try:
        return ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return None


def annotation(node: ast.expr | None) -> str:
    return ast.unparse(node) if node is not None else ""


def signature(node: ast.FunctionDef | ast.AsyncFunctionDef, *, method: bool) -> str:
    args = node.args
    values: list[str] = []
    positional = [*args.posonlyargs, *args.args]
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    for arg, default in zip(positional, defaults):
        if method and arg.arg in {"self", "cls"}:
            continue
        value = arg.arg + (f": {annotation(arg.annotation)}" if arg.annotation else "")
        if default is not None:
            value += f" = {ast.unparse(default)}"
        values.append(value)
    if args.vararg:
        values.append(f"*{args.vararg.arg}")
    elif args.kwonlyargs:
        values.append("*")
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        value = arg.arg + (f": {annotation(arg.annotation)}" if arg.annotation else "")
        if default is not None:
            value += f" = {ast.unparse(default)}"
        values.append(value)
    if args.kwarg:
        values.append(f"**{args.kwarg.arg}")
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    result = f"{prefix}{node.name}({', '.join(values)})"
    if node.returns:
        result += f" -> {annotation(node.returns)}"
    return result


def purpose(node: ast.AST, owner: str | None = None) -> str:
    doc = ast.get_docstring(node)
    if doc:
        value = " ".join(part.strip() for part in doc.splitlines() if part.strip())
        return value.split(". ", 1)[0].rstrip(".") + "."
    name = getattr(node, "name", "symbol")
    visibility = "Internal" if name.startswith("_") else "Public"
    subject = f"`{owner}`" if owner else "this module"
    known = {
        "to_dict": f"Serialize {subject} to a dictionary.",
        "from_dict": f"Construct {subject} from a dictionary.",
        "start": f"Start {subject} and its owned resources.",
        "stop": f"Stop {subject} and release its owned resources.",
        "close": f"Release resources owned by {subject}.",
        "run": f"Run the primary operation implemented by {subject}.",
        "chat": f"Execute a provider-backed chat turn through {subject}.",
        "send": f"Send a message through {subject}.",
    }
    return known.get(name, f"{visibility} `{name}` implementation on {subject}; the linked source is authoritative.")


def source_link(path: Path, line: int, depth: int = 3) -> str:
    rel = path.relative_to(ROOT).as_posix()
    return f"[`{rel}:{line}`]({'../' * depth}{rel}#L{line})"


def module_nodes(tree: ast.Module) -> list[ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef]:
    top_level = [node for node in tree.body if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))]
    top_level_ids = {id(node) for node in top_level}
    nested_classes = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.ClassDef) and id(node) not in top_level_ids
    ]
    return sorted([*top_level, *nested_classes], key=lambda node: node.lineno)


def group_for(path: Path) -> str:
    rel = path.relative_to(ROOT)
    return rel.parts[1] if len(rel.parts) > 2 else "package-root"


def group_filename(group: str) -> str:
    """Avoid generated names that agent runtimes treat as instructions."""
    filename = f"{group}.md"
    if filename.casefold() in RESERVED_INSTRUCTION_FILENAMES:
        return f"{group}-package.md"
    return filename


def render_group(group: str, paths: list[Path]) -> str:
    lines = [f"# Python Symbols: {group}", "", NOTICE, "", "Includes public and underscore-prefixed implementation symbols plus nested classes so every declared callable remains discoverable.", ""]
    symbol_count = 0
    method_count = 0
    for path in paths:
        tree = parse(path)
        if tree is None:
            continue
        nodes = module_nodes(tree)
        if not nodes:
            continue
        module = ".".join(path.relative_to(ROOT).with_suffix("").parts)
        lines.extend([f"## `{module}`", ""])
        for node in nodes:
            symbol_count += 1
            visibility = "internal" if node.name.startswith("_") else "public"
            if isinstance(node, ast.ClassDef):
                bases = ", ".join(ast.unparse(base) for base in node.bases)
                declaration = f"class {node.name}" + (f"({bases})" if bases else "")
                lines.extend([f"### `{node.name}` ({visibility})", "", f"`{declaration}`", "", f"Source: {source_link(path, node.lineno)}", "", purpose(node), ""])
                methods = [item for item in node.body if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))]
                if methods:
                    lines.extend(["| Method | Visibility | Purpose | Source |", "|---|---|---|---|"])
                    for method in methods:
                        method_count += 1
                        sig = signature(method, method=True).replace("|", "\\|")
                        description = purpose(method, node.name).replace("|", "\\|")
                        method_visibility = "internal" if method.name.startswith("_") else "public"
                        lines.append(f"| `{sig}` | {method_visibility} | {description} | {source_link(path, method.lineno)} |")
                    lines.append("")
            else:
                sig = signature(node, method=False)
                lines.extend([f"### `{node.name}` ({visibility})", "", f"`{sig}`  ", f"Source: {source_link(path, node.lineno)}", "", purpose(node), ""])
    lines[5:5] = [f"Inventory: **{symbol_count} declared symbols** and **{method_count} class methods**.", ""]
    return "\n".join(lines).rstrip() + "\n"


def python_references() -> dict[Path, str]:
    grouped: dict[str, list[Path]] = defaultdict(list)
    for path in sorted((ROOT / "flyto_ai").rglob("*.py")):
        tree = parse(path)
        if tree and module_nodes(tree):
            grouped[group_for(path)].append(path)
    result: dict[Path, str] = {}
    index = ["# Python Symbol Index", "", NOTICE, "", "All module-level functions/classes, nested classes, and direct class methods are included, including internal implementation symbols.", ""]
    for group, paths in sorted(grouped.items()):
        filename = group_filename(group)
        top = sum(len(module_nodes(parse(path))) for path in paths if parse(path))
        methods = sum(
            sum(len([item for item in node.body if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))]) for node in module_nodes(tree) if isinstance(node, ast.ClassDef))
            for path in paths
            if (tree := parse(path)) is not None
        )
        index.append(f"- [{group}]({filename}): {len(paths)} modules, {top} top-level symbols, {methods} methods")
        result[PYTHON_REFERENCE / filename] = render_group(group, paths)
    result[PYTHON_REFERENCE / "README.md"] = "\n".join(index).rstrip() + "\n"
    return result


ENVIRONMENT_READS = {
    "os.getenv", "_os.getenv", "os.environ.get", "_os.environ.get", "environ.get",
}
ENVIRONMENT_NAME = re.compile(r"[A-Z][A-Z0-9_]+")


def environment_constants(tree: ast.Module) -> dict[str, str]:
    """Map module-level constants that hold a statically provable variable name."""
    constants: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        value = node.value
        if not isinstance(value, ast.Constant) or not isinstance(value.value, str):
            continue
        if not ENVIRONMENT_NAME.fullmatch(value.value):
            continue
        for target in targets:
            if isinstance(target, ast.Name):
                constants[target.id] = value.value
    return constants


def environment_helpers(tree: ast.Module) -> dict[str, tuple[int, int | None]]:
    """Find functions that really read the environment through a parameter.

    Returns helper name -> (key parameter index, default parameter index). Only
    a function whose body passes one of its own parameters to a known
    environment read qualifies, so an arbitrary string-taking helper is never
    mistaken for an environment surface.
    """
    helpers: dict[str, tuple[int, int | None]] = {}
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        positions = {
            argument.arg: index
            for index, argument in enumerate(node.args.posonlyargs + node.args.args)
        }
        for inner in ast.walk(node):
            if not isinstance(inner, ast.Call) or not inner.args:
                continue
            if ast.unparse(inner.func) not in ENVIRONMENT_READS:
                continue
            key = inner.args[0]
            if not isinstance(key, ast.Name) or key.id not in positions:
                continue
            default = inner.args[1] if len(inner.args) > 1 else None
            default_index = (
                positions.get(default.id) if isinstance(default, ast.Name) else None
            )
            helpers[node.name] = (positions[key.id], default_index)
            break
    return helpers


def environment_reference() -> str:
    observations: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for path in [*sorted((ROOT / "flyto_ai").rglob("*.py")), *sorted((ROOT / "scripts").rglob("*.py"))]:
        tree = parse(path)
        if tree is None:
            continue
        rel = path.relative_to(ROOT).as_posix()
        constants = environment_constants(tree)
        helpers = environment_helpers(tree)
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call) or not node.args:
                continue
            called = ast.unparse(node.func)
            if called in ENVIRONMENT_READS:
                key_index, default_index = 0, 1
            elif called in helpers:
                key_index, default_index = helpers[called]
            else:
                continue
            if key_index >= len(node.args):
                continue
            key = node.args[key_index]
            if isinstance(key, ast.Constant) and isinstance(key.value, str):
                name = key.value
            elif isinstance(key, ast.Name) and key.id in constants:
                # A module constant is as statically provable as a literal.
                name = constants[key.id]
            else:
                continue
            if not ENVIRONMENT_NAME.fullmatch(name):
                continue
            if default_index is not None and default_index < len(node.args):
                default = ast.unparse(node.args[default_index])
            else:
                default = "required/None"
            observations[name].add((default, rel))
    lines = ["# Environment Variable Reference", "", NOTICE, "", "Every statically named environment read in package and Python scripts. Credentials belong in deployment secrets, never committed files.", "", "| Variable | Observed defaults | Owners |", "|---|---|---|"]
    for key, values in sorted(observations.items()):
        defaults = ", ".join(sorted({value[0] for value in values})).replace("|", "\\|")
        owners = ", ".join(f"`{value}`" for value in sorted({value[1] for value in values}))
        lines.append(f"| `{key}` | `{defaults}` | {owners} |")
    return "\n".join(lines).rstrip() + "\n"


ARGUMENT_FALLBACK = "See argparse declaration for behavior/default."


def module_string_constants(tree: ast.Module) -> dict[str, str]:
    """Map every module-level `NAME = "literal"` binding in one file."""
    constants: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        value = node.value
        if not isinstance(value, ast.Constant) or not isinstance(value.value, str):
            continue
        for target in targets:
            if isinstance(target, ast.Name):
                constants[target.id] = value.value
    return constants


def static_text(node: ast.expr, constants: dict[str, str]) -> str | None:
    """Resolve one expression to text, or None when it is not provably static.

    Only string literals, same-module string constants, and concatenation of
    those resolve. No application code is imported or executed, and no
    runtime-only value is guessed.
    """
    if isinstance(node, ast.Constant) and isinstance(node.value, (str, int, float)):
        return str(node.value)
    if isinstance(node, ast.Name):
        return constants.get(node.id)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left = static_text(node.left, constants)
        right = static_text(node.right, constants)
        return None if left is None or right is None else left + right
    if isinstance(node, ast.JoinedStr):
        parts = []
        for piece in node.values:
            if isinstance(piece, ast.Constant) and isinstance(piece.value, str):
                parts.append(piece.value)
            elif isinstance(piece, ast.FormattedValue):
                resolved = static_text(piece.value, constants)
                if resolved is None:
                    return None
                parts.append(resolved)
            else:
                return None
        return "".join(parts)
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
        if node.func.attr != "format":
            return None
        template = static_text(node.func.value, constants)
        if template is None:
            return None
        positional = [static_text(argument, constants) for argument in node.args]
        named = {
            keyword.arg: static_text(keyword.value, constants)
            for keyword in node.keywords if keyword.arg
        }
        if any(item is None for item in positional) or any(
            item is None for item in named.values()
        ):
            return None
        # Substitute by scanning, never by calling str.format, so a template
        # can never reach attribute or index access on a real object.
        rendered, index = [], 0
        remaining = template
        while True:
            start = remaining.find("{")
            if start < 0:
                rendered.append(remaining)
                break
            end = remaining.find("}", start)
            if end < 0:
                rendered.append(remaining)
                break
            field = remaining[start + 1:end]
            rendered.append(remaining[:start])
            if field == "":
                if index >= len(positional):
                    return None
                rendered.append(positional[index])
                index += 1
            elif field.isdigit():
                position = int(field)
                if position >= len(positional):
                    return None
                rendered.append(positional[position])
            elif field in named:
                rendered.append(named[field])
            else:
                return None
            remaining = remaining[end + 1:]
        return "".join(rendered)
    return None


def literal_parts(node: ast.expr) -> str:
    """Safe fallback: keep only the static literal parts of an expression."""
    return " ".join(
        literal.value.strip() for literal in ast.walk(node)
        if isinstance(literal, ast.Constant) and isinstance(literal.value, str)
        and literal.value.strip()
    )


def argument_row(node: ast.Call, constants: dict[str, str] | None = None) -> tuple[str, str]:
    """Project one `add_argument(...)` call into its names and help text."""
    constants = constants or {}
    names = ", ".join(
        argument.value for argument in node.args[:2]
        if isinstance(argument, ast.Constant) and isinstance(argument.value, str)
    )
    description = ARGUMENT_FALLBACK
    for keyword in node.keywords:
        if keyword.arg != "help":
            continue
        resolved = static_text(keyword.value, constants)
        if resolved is None:
            resolved = literal_parts(keyword.value)
        description = resolved.strip() or ARGUMENT_FALLBACK
    return names or "dynamic", description


def parser_helpers(
    tree: ast.Module, constants: dict[str, str] | None = None,
) -> dict[str, list[tuple[str, str, int]]]:
    """Collect arguments that a helper adds to whichever parser it is given.

    `flyto_ai.cli` shares options between `code-mcp` and `code-serve` through
    one helper, so the inventory must attribute them to every parser passed in
    rather than dropping them or inventing a fake owner.
    """
    helpers: dict[str, list[tuple[str, str, int]]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        parameters = {argument.arg for argument in node.args.posonlyargs + node.args.args}
        if not parameters:
            continue
        added: list[tuple[str, str, int]] = []
        for inner in ast.walk(node):
            if not isinstance(inner, ast.Call) or not isinstance(inner.func, ast.Attribute):
                continue
            if inner.func.attr != "add_argument":
                continue
            if not isinstance(inner.func.value, ast.Name) or inner.func.value.id not in parameters:
                continue
            names, description = argument_row(inner, constants)
            added.append((names, description, inner.lineno))
        if added:
            helpers[node.name] = sorted(added, key=lambda item: item[2])
    return helpers


def cli_reference() -> str:
    path = ROOT / "flyto_ai" / "cli.py"
    tree = parse(path)
    rows: list[tuple[tuple[int, int], str, str, str, int]] = []
    parser_vars: dict[str, str] = {"parser": "root", "sub": "root"}
    constants = module_string_constants(tree) if tree is not None else {}
    helpers = parser_helpers(tree, constants) if tree is not None else {}
    for node in ast.walk(tree) if tree is not None else []:
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
            call = node.value
            if isinstance(call.func, ast.Attribute) and call.func.attr == "add_parser":
                command = command_name(call)
                if command:
                    for target in node.targets:
                        if isinstance(target, ast.Name):
                            parser_vars[target.id] = command
    for node in ast.walk(tree) if tree is not None else []:
        if not isinstance(node, ast.Call):
            continue
        if isinstance(node.func, ast.Attribute) and node.func.attr == "add_parser":
            command = command_name(node)
            if command:
                rows.append(((node.lineno, 0), command, "command", command_help(node), node.lineno))
            continue
        if isinstance(node.func, ast.Attribute) and node.func.attr == "add_argument":
            if not isinstance(node.func.value, ast.Name):
                continue
            owner_var = node.func.value.id
            if owner_var not in parser_vars and owner_var not in {"parser", "sub"}:
                # A helper parameter; attributed at each call site instead.
                if any(owner_var in {
                    argument.arg
                    for argument in helper.args.posonlyargs + helper.args.args
                } for helper in ast.walk(tree) if isinstance(helper, (ast.FunctionDef, ast.AsyncFunctionDef))):
                    continue
            names, description = argument_row(node, constants)
            owner = parser_vars.get(owner_var, owner_var)
            rows.append(((node.lineno, 0), owner, names, description, node.lineno))
            continue
        if isinstance(node.func, ast.Name) and node.func.id in helpers and node.args:
            target = node.args[0]
            if not isinstance(target, ast.Name):
                continue
            owner = parser_vars.get(target.id, target.id)
            for index, (names, description, declared) in enumerate(helpers[node.func.id], 1):
                rows.append(((node.lineno, index), owner, names, description, declared))
    output = ["# CLI Reference", "", NOTICE, "", "Entrypoints: `flyto-ai` and `python -m flyto_ai`. `flyto-ai-mcp` starts the STDIO MCP server.", "", "| Command owner | Command / option | Purpose | Source |", "|---|---|---|---|"]
    for _key, owner, item, description, line in sorted(rows, key=lambda row: row[0]):
        output.append(f"| `{owner}` | `{item}` | {md(description)} | {source_link(path, line, depth=2)} |")
    return "\n".join(output).rstrip() + "\n"


def command_name(node: ast.Call) -> str:
    if node.args and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str):
        return node.args[0].value
    return ""


def command_help(node: ast.Call) -> str:
    for keyword in node.keywords:
        if keyword.arg == "help" and isinstance(keyword.value, ast.Constant):
            if isinstance(keyword.value.value, str):
                return keyword.value.value
    return "Subcommand"


def tool_reference() -> str:
    rows: list[tuple[str, str, str, int]] = []
    for path in sorted((ROOT / "flyto_ai" / "tools").glob("*.py")) + [ROOT / "flyto_ai" / "mcp_server.py"]:
        tree = parse(path)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Dict):
                continue
            values = {}
            for key, value in zip(node.keys, node.values):
                if isinstance(key, ast.Constant) and isinstance(key.value, str):
                    values[key.value] = value
            name_node = values.get("name")
            if not isinstance(name_node, ast.Constant) or not isinstance(name_node.value, str):
                continue
            description_node = values.get("description")
            description = description_node.value if isinstance(description_node, ast.Constant) and isinstance(description_node.value, str) else "Tool or protocol definition."
            rows.append((name_node.value, description.replace("\n", " "), path.relative_to(ROOT).as_posix(), node.lineno))
    unique = sorted(set(rows), key=lambda row: (row[0], row[2], row[3]))
    lines = ["# Tool And MCP Reference", "", NOTICE, "", "Static Flyto2 AI tool definitions. Registry-backed `flyto-core` tools are discovered at runtime and described by the capability manifest rather than copied here.", "", "| Tool | Responsibility | Owner | Source |", "|---|---|---|---|"]
    for name, description, rel, line in unique:
        lines.append(f"| `{name}` | {md(description)} | `{rel}` | {source_link(ROOT / rel, line, depth=2)} |")
    return "\n".join(lines).rstrip() + "\n"


def scripts_reference() -> str:
    lines = ["# Maintainer Script Reference", "", NOTICE, "", "Scripts are operator tools, not stable Python APIs. Review side effects and required credentials before use.", "", "| Script | Purpose |", "|---|---|"]
    for path in sorted((ROOT / "scripts").iterdir()):
        if not path.is_file() or path.name == Path(__file__).name:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if path.suffix == ".py" and (tree := parse(path)) is not None:
            description = ast.get_docstring(tree) or "Python maintainer utility."
        else:
            description = next((line.lstrip("# ").strip() for line in text.splitlines() if line.startswith("#") and not line.startswith("#!")), "Shell maintainer utility.")
        lines.append(f"| [`{path.name}`](../../scripts/{path.name}) | {md(' '.join(description.split()))} |")
    return "\n".join(lines).rstrip() + "\n"


def index_reference() -> str:
    return """# Generated Reference

> Generated by `python3 scripts/generate_reference.py`. Do not edit manually.

- [Python symbols](python/README.md): every top-level function/class and direct class method, including internal symbols.
- [CLI](cli.md): commands and options declared by the CLI parser.
- [Tools and MCP](tools-and-mcp.md): static AI/MCP tool definitions and runtime discovery boundary.
- [Environment](environment.md): every statically named environment read.
- [Maintainer scripts](scripts.md): release/demo and other operator utilities.

Run `python3 scripts/generate_reference.py`; CI uses `--check` to reject drift.
"""


def normalize_markdown(content: str) -> str:
    """Return stable Markdown with no trailing whitespace and one final newline."""
    return "\n".join(line.rstrip() for line in content.splitlines()) + "\n"


def outputs() -> dict[Path, str]:
    result = python_references()
    result[REFERENCE / "README.md"] = index_reference()
    result[REFERENCE / "cli.md"] = cli_reference()
    result[REFERENCE / "tools-and-mcp.md"] = tool_reference()
    result[REFERENCE / "environment.md"] = environment_reference()
    result[REFERENCE / "scripts.md"] = scripts_reference()
    return {path: normalize_markdown(content) for path, content in result.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = outputs()
    if args.check:
        stale = [path for path, content in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        extras = [path for path in PYTHON_REFERENCE.glob("*.md") if path not in expected]
        if stale or extras:
            for path in [*stale, *extras]:
                print(f"stale generated reference: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"{len(expected)} generated reference files are current")
        return 0
    if PYTHON_REFERENCE.exists():
        for path in PYTHON_REFERENCE.glob("*.md"):
            path.unlink()
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(expected)} generated reference files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
